### ISSUE TITLE
Update attachment screen for claim

### ISSUE THREAD

**Issue by simonas-notcat** [gluon-project/gluon-design#19]
* Without claim
  * With created claim

**Comment by ziggy-notcat** [comment]
![Desktop HD Send-Request_Attachment.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b039758fe90647422623c01b03f4fa4f73cbe41730c0a010abe5d4a1f06a3a3dc78e2a436628f0d5dbed46d5a21c73e43f8b9801fbf00ef25821d87b3be9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca50f149e64e54a6113f67f43b.jpg)
![Desktop HD Send-Request_Attachment_Claim.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b039758fe90647422623c01b03f4fa4f73cbe41730c0a010ac332040e1da1eb9539e6f4632adf0f4fffdb7f5a25906e14acbdd71ebc53ee21894f85b7e98f4592ea3827f5979d0d6f405147d4a61760e28b41da5af741e04857ac143464e573377944970c38.jpg)
![Desktop HD Send-Request_Attachment_Photo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b039758fe90647422623c01b03f4fa4f73cbe41730c0a010ac321000000a3eb9539e6f4632adf0f4fffdb7f5a25906e14acbdd71ebc53ee21894f85b7e98f4592ea3827f5979d0d6f405147d4a61760e28b41da59f141e04857ac143464e573317841950c38.jpg)
![Desktop HD Send-Request_Attachment_Photo+Claim.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b039758fe90647422623c01b03f4fa4f73cbe41730c0a010ac321000000a3e2fa77f7ef6162964e4baf8e370a27822f1bbebdd349ec04ba25de4e86e4e88b4ec0e83c70e282dd4d3b1c17049bbd0c6bf4c6169112a309f34747a6123c62e3743e7b45931d722e6d6627b9b1.jpg)
