### ISSUE TITLE
Claim creation screen

### ISSUE THREAD

**Issue by simonas-notcat** [gluon-project/gluon-design#20]
* Date created
  * Expiration date
  * Issuer (Avatar, Name, Address)
  * Subject (Avatar, Name, Address)
  * Claim data: x = y ( "Skill" = "Android Developer")

**Comment by ziggy-notcat** [comment]
![Desktop HD Send-Request_Attachment_Claim Creation.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b039758fe90647422623c01b03f4fa4f73cbe41730c0a010ac332040e1da1e9fa69f3e77829d50219f1c32d1d2b9c6842e8aa880dba50ec738e4f80e3bd891e94e93f25e78ada4a374c071d8bed4127e2c8159c07ab12ab1817b6192462ee7c3779459c19772b6f6522a3f5db44ca.jpg)
