### ISSUE TITLE
Claim in Feed screen

### ISSUE THREAD

**Issue by simonas-notcat** [gluon-project/gluon-design#21]

**Comment by ziggy-notcat** [comment]
![Desktop HD Feed.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0c2e998d0f5000126c5bee/125516c66e82c728ace21e0d46cc918928968cb9cfc19b038258f5906b0a65633b0ba92e7391a172fd177a070c5a4ea914595c16a8f88b2ba6b76975830e09e8d37f4366846c4ff8e7df46f554f832815d87b7b68b49c2e03a27e0898f49361b020ac4.jpg)
