### ISSUE TITLE
Token balances screen sketch design

### ISSUE THREAD

**Issue by simonas-notcat** [gluon-project/gluon-design#4]

**Comment by ziggy-notcat** [comment]
![desktop hd wallet](https://user-images.githubusercontent.com/39312571/40282047-a32797e0-5c71-11e8-81c3-a92f5ecf76cd.jpg)
![desktop hd wallet-token info](https://user-images.githubusercontent.com/39312571/40282048-aab70752-5c71-11e8-97fd-91ce736a418e.jpg)
